### ISSUE TITLE
Example Template

### ISSUE THREAD

**Issue by morgandonze** [maiertech/gatsby-themes#2]
Forgive me, but I'm having trouble creating a working template. Do you have an example you could provide?

In `node_modules/@maiertech/gatsby-plugin-blog/gatsby-node.js`, it says 

```
    } // Template uses `path` to query page data.
```

but I don't understand how to do this. I understand how I could do this if 
`pageResources.page.path` contained a relative path I could use in a query, but that seems to contain the url path.

**Comment by maiertech** [comment]
Work in progress. Check the `blog` branch: https://github.com/maiertech/gatsby-themes/tree/blog. Or look at this example I'm working on: https://github.com/UNDataForum/gatsby-themes. The `main-website-demo` should work fine.
